### ISSUE TITLE
Regression in client-side on.* attributes?

### ISSUE THREAD

**Issue by cata** [dotnet-websharper/ui#144]
Hi guys,

We've noticed that in `WebSharper.UI 4.1.0.34`  some of the `on.*` event handlers have reverted to using quotations on the client.
This re-introduces some of the limitations present in Websharper 3.x (such as being unable to use generic inner functions, etc.)  - and prevents our client from building.
Some of the culprits (so far) are: `on.click`, `on.touchStart` and `on.touchMove`

I was wondering if you are aware of this - I'm hoping it can be reverted.

**Comment by granicz** [comment]
(More discussion on this [here](https://forums.websharper.com/topic/84133).)

**Comment by cata** [comment]
Thank you, @granicz!

**Comment by Martin521** [comment]
The most simple and least disturbing work-around, in my case, is to use an anonymous function in the template call to get rid of the var collection argument.
Shown in the  [same snippet](http://try.websharper.com/snippet/Martin%20000/0000Gv).

**Comment by Tarmil** [comment]
I'm coming back to this issue, and here are my findings.

The fundamental reason why this is happening is that we added `[<ReflectedDefinition>]` on the (already existing) version of `on.*` that takes a quotation. This allows you to call `on.click (fun ...)` in the middle of server-side code, without explicit `<@ ... @>`, and have it translated to JavaScript. However, because of this, a call to `on.click (fun ...)` is now ambiguous, and the quotation version always takes precedence:

```fsharp
module WebSharper.UI.Html
type on =
    static member click (f: Expr<Element -> Event -> unit>) = ()

module WebSharper.UI.Client
type Html.on with
    static member click (f: Element -> Event -> unit) = ()

module MyUserCode
on.click (fun _ _ -> ()) // <- this calls the Expr version
```

At the time we didn't really see this as a problem, because we made sure that the Expr version compiles to the same JavaScript as the non-Expr version. So we just removed the non-Expr version, as we figured it was now redundant.

However, the Expr version causes the present limitation. So we do need to re-introduce the non-Expr version and find a way to make it take precedence. The way I have found is that `UI.Client`, instead of defining extension methods on `Html.on`, should define its own `on` type. This will work as expected *as long as you open `.Client` **after** `.Html`*:

```fsharp
open WebSharper.UI.Html
open WebSharper.UI.Client

on.click (fun _ _ -> ()) // this will call the non-Expr version
```
