### ISSUE TITLE
Templating breaks inside <table>

### ISSUE THREAD

**Issue by granicz** [dotnet-websharper/ui#216]
See https://gitter.im/intellifactory/websharper?at=5fee8364acd1e516f8c71ee7 for details

(only tested in SPAs with `Bind()`)

**Comment by granicz** [comment]
@Tarmil Can you take a look? Thanks!

**Comment by Tarmil** [comment]
I think that's because HTML is actually parsed weirdly by browsers (as a standard) when some forbidden nestings happen, such as in your case `div` directly inside `tbody` or `tr` directly inside `div`. There is [some code](https://github.com/dotnet-websharper/ui/blob/78aaf0684c006f4ce0cad208fd40849ad8d73c75/WebSharper.UI.Templating.Runtime/Runtime.fs#L464) that helps deal with it in sitelets, based on [this article](https://krasimirtsonev.com/blog/article/Revealing-the-magic-how-to-properly-convert-HTML-string-to-a-DOM-element), but if your SPA page contains these combinations then there is nothing that WebSharper can do.

So what you need to do is remove the divs and move the `ws-*` attributes around so that the final effect is the same but the structure looks like valid HTML, for example something like this:

```html
<table>
    <tbody ws-hole="CartItems" ws-children-template="CartItem">
        <tr>
            <td ...>
```

Or this:

```html
<table>
    <tbody>
        <tr ws-replace="CartItems"></tr>
        <tr ws-template="CartItem">
            <td ...>
```
